### ISSUE TITLE
[MultiZ] (MAP + CODE) Понятие пола и потолка, гравитации, совместно с этим связанный баг шаттлов (!).

### ISSUE THREAD

**Issue by FighterX2500** [FighterX2500/SovietBay#121]
Благодаря г-ну Aleksix, у нас исчез опасный баг, однако не решен другой.

Вообще логично, что теперь для постройки конструкции в космосе необходимо строить первым делом потолок, а после сам отсек. Господа разработчики Беевцы забыли доработать карту и добавить потолки отсекам на всех Z-уровнях, но т.к. turf не open space, разгерметизации нет. А проникнуть можно. Скорее тут больше дело мапинга, а не 
Кроме того, возникает (!) баг шаттлов. Этот баг вызван возможностью перемещения шаттлов по палубам (Z-уровням) и созданием open-space на Z-уровнях выше.
В кратце, у ШАТТЛОВ НЕТ ПОТОЛКА! И это разгерметизирует шаттлов. Итог очевиден.

И open space образуется на всех Z-уровнях выше, причем в точности как зона шаттла.
Гравитация есть, но не падаешь в неё. Скорее как просто пол.

Есть такой вариант решения, не знаю, насколько сложным он будет:
1) Создание пола над зоной шаттла, если шаттл в эту зону попал. Тут однако, такое дело. Open Space создается на всех Z-уровнях, и если шаттл, скажем, на первой палубе, то на третьей и четвертой логично тоже будет open space, однако он будет как пол и можно будет просто перемещаться на нём.
Для зон шаттлов можно добавить какую-нибудь специальную проверку замены\удаления потолка. 

Странно, что беевцы начали тестить Z-уровневую станцию, при этом не выполнив самые главные фиксы.

Прикладываю скриншоты по проблемам:
1) Шаттл, состыкованный со станцией. Как видно, экипаж умер. От чего?
http://puu.sh/sUYyw/2f027898f0.png
http://puu.sh/sUYEW/36492f1a67.png

2) Корабль без потолка.
http://puu.sh/sUYVP/b33b0a2ada.png
http://puu.sh/sUYX6/508781ef5b.png

Маперам же следует сделать потолки для всех отсеков, а то как в этой картинке получается (Без разгерметизации):
http://i45.tinypic.com/348q63o.png

Эти фиксы принесут карте абсолютно полную играбельность, позволяя шаттлам нормально перемещаться между уровнями без декомпрессии, а так же блокируя игроков от побега в космос.

**Comment by Bradley-Blya** [comment]
Уберите возможность перемещаться вверх-вниз через полы/потолки, потому уже про шаттлы думать можно.

**Comment by FighterX2500** [comment]
> Уберите возможность перемещаться вверх-вниз через полы/потолки, потом уже про шаттлы думать можно.

Это уже пофиксили. В самом начале же написал.

> Благодаря г-ну Aleksix, у нас исчез опасный баг, однако не решен другой.

**Comment by FighterX2500** [comment]
Пофиксено.
