### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by FighterX2500** [FighterX2500/SovietBay#13]
Ребятушки, вынесите все эмоции в отдельную вкладочку, что бы не нужно было писать say *emote

Тоже касается киборгов и прочее.

**Comment by aleksix** [comment]
А так часто их используют? Можно, конечно, но ведь их там дофига, некрасиво будет.

**Comment by FighterX2500** [comment]
Пойдет, их вполне можно часто использовать, чем писать через /me
