### ISSUE TITLE
Разобраться и скомпилировать релиз-версию проекта

### ISSUE THREAD

**Issue by Divix01** [FighterX2500/SovietBay#29]
На англоязычных форумах Byond-а пишут, что это должно уменьшить лаги и повысить производительность, но при последней попытке убрать define DEBUG всё полетело. Кто сможет, тому респект и уважение.

PS В Dream Daemon есть кнопочка World->Profile, она должна помочь с отладкой и оптимизацией (работает только если есть #define DEBUG)

**Comment by aleksix** [comment]
Какая версия BYOND, что всё полетела?

**Comment by Divix01** [comment]
Вопрос к барсу, но вроде stable Version 509.1319 же. Других просто нету, на бете не скомпилировать сервер без бета-бьонда. Это важно?)

**Comment by aleksix** [comment]
Окей, проблема с компиляцией релизной версии до сих пор есть? 510.1338, отключил debug в компиляторе и убрал из одного файла, всё относительно нормально работает.

**Comment by FighterX2500** [comment]
Не сработала.

**Comment by aleksix** [comment]
А что-то выдавала?
