### ISSUE TITLE
Лаги от мая 2016

### ISSUE THREAD

**Issue by Divix01** [FighterX2500/SovietBay#54]
После некоторых апдейтов (слияние с беем) в начале мая появились серьезные лаги: на сервере педали вроде как обнаружили, что проблема с грязью (garbage?) - очень часто удаляется. И действительно, находясь или пролетая над грязнющим от передвижений (т.е. не от крови и прочего) медбее, можно было ощутить слайд-шоу, хотя в других частях станции ситуация была намного лучше (но другая часть станции была чище).

**Comment by Wyderar** [comment]
Не тот garbage. Это - мусорные данные. Вот допустим - на станции... 1600 грязных тайлов. Админ удаляет грязь. Удалит всё сразу - завалит сервер. Поэтому раз в ~секунду проходит удаление нескольких кусков грязи. Ещё в мусор скидываются отработанные переменные и т.д.

**Comment by Divix01** [comment]
Ясно. Но факт остается фактом - лаги над медбеем настолько дикие со временем, что играть невозможно (это хорошо, если ещё не вылетит пару раз).

**Comment by FighterX2500** [comment]
Лагов над медбеем более не было обнаружено. Это связано с обычными лагами Бея, которых как всегда, конечно же, в изобилии.
