### ISSUE TITLE
Генетические силы не работают

### ISSUE THREAD

**Issue by aleksix** [FighterX2500/SovietBay#81]
Из сил в генетике работает только халк. Остальные пишет, что появились, для некоторых даже есть команда, но они не активируются. Сами силы работают, игроки их получали через артефакты.

**Comment by FighterX2500** [comment]
Да, в идеале было бы неплохо перенести систему генетики с /vg/station - там она проработана.

**Comment by sasichkamega** [comment]
Робят 100% следующие силы:

- Халк
- Телепатия
- Малый размер
- Реген
- Телекинез
- Иксрей
- *Все болезни*

Не работают:
- Скорость
- Иммунитет к шоку
- FIRE

**Comment by aleksix** [comment]
Т.е. ты их получил генетикой? Люди жаловались, что силы робят, но получить их можно только через артефакты.
