### ISSUE TITLE
Мобы под контролем игрков сами преследуют жертву

### ISSUE THREAD

**Issue by aleksix** [FighterX2500/SovietBay#82]
Контролируемые игроками мобы сами нападают на жертву. Может и фича, не будет сверхтрусливых карпов, ждущих в засаде.

**Comment by sasichkamega** [comment]
Вроде как решил эту проблему. Будем посмотреть крче.

**Comment by aleksix** [comment]
Мне закрывать?

**Comment by sasichkamega** [comment]
Оставь пока. Нужно затестить еще.
